#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2017

# set clone depth
clone_depth: 1

# clone directory
clone_folder: c:\projects\panda3d-thirdparty

# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if (Test-Path env:TRIGGER_NAME) {
        Update-AppveyorBuild -Message "Build by $env:TRIGGER_BUILD_VERSION in $env:TRIGGER_NAME"
    }
- git --version
- cmake --version

# environment variables
environment:
    CMAKE_PREFIX_PATH: C:\projects\_install;C:\projects\_cache;
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64

# this is how to allow failing jobs in the matrix
matrix:
    fast_finish: true   # set this flag to immediately finish build once one of the jobs fails.

# build cache to preserve files/folders between builds
cache:
    - C:\projects\_cache

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
- MixForDebug
- Release

build:
    parallel: true                  # enable MSBuild parallel builds

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: (mkdir _build) -and (pushd _build)
- cmd: >-
    if "%CONFIGURATION%"=="MixForDebug" (
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="C:/projects/_install/panda3d-thirdparty"
    -DBUILD_ARTOOLKIT=OFF
    -DBUILD_BULLET=OFF
    -DBUILD_FCOLLADA=OFF
    -DBUILD_FFMPEG=OFF
    -DBUILD_NVIDIACG=OFF
    -DBUILD_ODE=OFF
    -DBUILD_OPENSSL=OFF
    -DBUILD_VRPN=OFF
    -Dbuild_mixfordebug=ON
    ) else (
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="C:/projects/_install/panda3d-thirdparty"
    -DBUILD_ARTOOLKIT=OFF
    -DBUILD_BULLET=OFF
    -DBUILD_FCOLLADA=OFF
    -DBUILD_FFMPEG=OFF
    -DBUILD_NVIDIACG=OFF
    -DBUILD_ODE=OFF
    -DBUILD_OPENSSL=OFF
    -DBUILD_VRPN=OFF
    )
- cmake --build . --config "Release" --target INSTALL
- ps: popd

after_build:
- 7z a panda3d-thirdparty.7z "C:/projects/_install/panda3d-thirdparty"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: panda3d-thirdparty.7z

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
- ps: >-
    if (($env:CONFIGURATION -eq "Release") -and ($env:APPVEYOR_REPO_BRANCH -eq "master")) {
        Start-AppveyorBuild -ApiKey $env:api_key -ProjectSlug 'panda3d' -EnvironmentVariables @{
            TRIGGER_NAME = $env:APPVEYOR_PROJECT_NAME
            TRIGGER_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION
        }
    }
