#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2015

# set clone depth
clone_depth: 1

# clone directory
clone_folder: c:\projects\panda3d-thirdparty

# scripts that are called at very beginning, before repo cloning
init:
- git --version
- cmake --version

# environment variables
environment:
    CMAKE_PREFIX_PATH: C:\projects\_install;C:\projects\_cache;
    CMAKE_GENERATOR: Visual Studio 14 2015 Win64

    matrix:
        - THIRDPARTY_GROUP: 0
        - THIRDPARTY_GROUP: 1

# this is how to allow failing jobs in the matrix
matrix:
    fast_finish: true   # set this flag to immediately finish build once one of the jobs fails.

# build cache to preserve files/folders between builds
cache:
    - C:\projects\_cache

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
- Release

build:
    parallel: true                  # enable MSBuild parallel builds

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: (mkdir _build) -and (pushd _build)
- cmd: >-
    if "%THIRDPARTY_GROUP%"=="0" (
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DDISABLE_ALL=ON
    -DBUILD_ZLIB=ON
    -DBUILD_PNG=ON
    -DBUILD_ASSIMP=ON
    -DBUILD_HARFBUZZ=ON
    -DBUILD_FREETYPE=ON
    -DBUILD_VORBIS=ON
    -DBUILD_JPEG=ON
    -DBUILD_SQUISH=ON
    -DBUILD_TIFF=ON
    -DBUILD_OPENEXR=ON
    -DBUILD_FFMPEG=ON
    ) else (
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DDISABLE_ALL=ON
    -DBUILD_BULLET=ON
    -DBUILD_FCOLLADA=ON
    -DBUILD_VRPN=ON
    -DBUILD_ODE=ON
    -DBUILD_ARTOOLKIT=ON
    -DBUILD_NVIDIACG=ON
    -DBUILD_OPENSSL=ON
    )
- cmake --build . --config "Release"
- ps: popd

after_build:
- 7z a panda3d-thirdparty.7z "C:/projects/panda3d-thirdparty/win-libs-vc14-x64"     # Visual Studio 14

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: panda3d-thirdparty.7z

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
