#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2015
- Visual Studio 2017 Preview
- Visual Studio 2017


# set clone depth
clone_depth: 1


# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if (Test-Path env:TRIGGER_NAME) {
        Update-AppveyorBuild -Message "Build by $env:TRIGGER_BUILD_VERSION in $env:TRIGGER_NAME"
    }
- git --version
- cmake --version


# environment variables
environment:
    INSTALL_PREFIX: C:/projects/_install


# this is how to allow failing jobs in the matrix
matrix:
    fast_finish: true   # set this flag to immediately finish build once one of the jobs fails.
    allow_failures:
        - image: Visual Studio 2017 Preview
    exclude:
        - configuration: MixForDebug
          image: Visual Studio 2015
        - configuration: MixForDebug
          image: Visual Studio 2017 Preview

# build cache to preserve files/folders between builds
#cache:


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
- MixForDebug
- Release

build:
    parallel: true                  # enable MSBuild parallel builds

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: mkdir _build
- ps: pushd _build

- cmd: >-
    if "%CONFIGURATION%"=="MixForDebug" (
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="%INSTALL_PREFIX%/panda3d-thirdparty"
    -DBUILD_ASSIMP=OFF
    -DBUILD_ARTOOLKIT=OFF
    -DBUILD_BULLET=OFF
    -DBUILD_FCOLLADA=OFF
    -DBUILD_FFMPEG=OFF
    -DBUILD_NVIDIACG=OFF
    -DBUILD_EIGEN=OFF
    -DBUILD_ODE=OFF
    -DBUILD_OPENSSL=OFF
    -DBUILD_VRPN=OFF
    -Dbuild_mixfordebug=ON
    ) else (
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="%INSTALL_PREFIX%/panda3d-thirdparty"
    -DBUILD_ASSIMP=OFF
    -DBUILD_ARTOOLKIT=OFF
    -DBUILD_BULLET=OFF
    -DBUILD_FCOLLADA=OFF
    -DBUILD_FFMPEG=OFF
    -DBUILD_NVIDIACG=OFF
    -DBUILD_EIGEN=OFF
    -DBUILD_ODE=OFF
    -DBUILD_OPENSSL=OFF
    -DBUILD_VRPN=OFF
    )
- cmd: cmake --build . --config "Release"

- ps: popd

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:

after_test:
- cmd: cmake --build _build --config "Release" --target install
- cmd: 7z a panda3d-thirdparty.7z "%INSTALL_PREFIX%/panda3d-thirdparty"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: panda3d-thirdparty.7z

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
- ps: >-
    if (($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") -and ($env:CONFIGURATION -eq "Release") -and ($env:APPVEYOR_REPO_BRANCH -eq "master")) {
        Start-AppveyorBuild -ApiKey $env:api_key -ProjectSlug 'panda3d' -EnvironmentVariables @{
            TRIGGER_NAME = $env:APPVEYOR_PROJECT_NAME
            TRIGGER_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION
        }
    }

#---------------------------------#
#       specializing matrix       #
#---------------------------------#

for:
-
    matrix:
        only:
            - image: Visual Studio 2015
    environment:
        CMAKE_GENERATOR: Visual Studio 14 2015 Win64

-
    matrix:
        only:
            - image: Visual Studio 2017
            - image: Visual Studio 2017 Preview
    environment:
        CMAKE_GENERATOR: Visual Studio 15 2017 Win64
