#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2015

# set clone depth
clone_depth: 1

# clone directory
clone_folder: c:\projects\panda3d-thirdparty

# scripts that are called at very beginning, before repo cloning
init:
- git --version
- cmake --version

# environment variables
environment:
    CMAKE_PREFIX_PATH: C:\projects\_install;C:\projects\_cache;
    CMAKE_GENERATOR: Visual Studio 14 2015 Win64

# this is how to allow failing jobs in the matrix
matrix:
    fast_finish: true   # set this flag to immediately finish build once one of the jobs fails.

# build cache to preserve files/folders between builds
cache:
    - C:\projects\_cache

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
- Release

build:
    parallel: true                  # enable MSBuild parallel builds

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: (mkdir _build) -and (pushd _build)
- cmd: >-
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DBUILD_EIGEN=OFF
- cmake --build . --config "Release" --target ALL_BUILD
- ps: popd

after_build:
- 7z a panda3d-thirdparty.7z "C:/projects/panda3d-thirdparty/win-libs-vc14"     # Visual Studio 14

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: panda3d-thirdparty.7z

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
