jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    matrix:
      vc140_release:
        BUILD_TOOLSET: 'vc140'
        BUILD_CONFIGURATION: 'release'
        CMAKE_TOOLSET: 'v140,host=x64'
      vc141_debug:
        BUILD_TOOLSET: 'vc141'
        BUILD_CONFIGURATION: 'debug'
        CMAKE_TOOLSET: 'host=x64'
      vc141_release:
        BUILD_TOOLSET: 'vc141'
        BUILD_CONFIGURATION: 'release'
        CMAKE_TOOLSET: 'host=x64'

  variables:
    REPO_NAME: 'panda3d-thirdparty'
    CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'

  steps:
  # configure & generate
  - task: CMake@1
    inputs:
      cmakeArgs: .. -G "$(CMAKE_GENERATOR)" -Wno-dev -T $(CMAKE_TOOLSET) -DCMAKE_INSTALL_PREFIX="$(Build.BinariesDirectory)/$(REPO_NAME)"

  # build
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --config $(BUILD_CONFIGURATION)

  # tests
  #- task

  # install
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --config $(BUILD_CONFIGURATION) --target install

  # packaging
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/$(REPO_NAME)'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(REPO_NAME).7z'

  # publish
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(REPO_NAME)-$(BUILD_TOOLSET)-$(BUILD_CONFIGURATION)'
