variables:
  REPO_NAME: 'panda3d-thirdparty'
  CMAKE_GENERATOR_PLATFORM: 'x64'
  BUILD_CONFIGURATION: 'release'
  BUILD_MIX_FOR_DEBUG: 'OFF'

jobs:
- job: Windows

  strategy:
    matrix:
      vc140-x86-release:
        ARCHITECTURE_SUFFIX: ''
        PANDA3D_TOOLS_SUFFIX: 'win32'
        BUILD_TOOLSET_VERSION: '140'
        CMAKE_GENERATOR_PLATFORM: 'Win32'
      vc140-x64-release:
        BUILD_TOOLSET_VERSION: '140'
      vc141-x86-debug:
        ARCHITECTURE_SUFFIX: ''
        PANDA3D_TOOLS_SUFFIX: 'win32'
        BUILD_CONFIGURATION: 'debug'
        BUILD_MIX_FOR_DEBUG: 'ON'
        CMAKE_GENERATOR_PLATFORM: 'Win32'
      vc141-x86-release:
        ARCHITECTURE_SUFFIX: ''
        PANDA3D_TOOLS_SUFFIX: 'win32'
        CMAKE_GENERATOR_PLATFORM: 'Win32'
      vc141-x64-debug:
        BUILD_CONFIGURATION: 'debug'
        BUILD_MIX_FOR_DEBUG: 'ON'
      vc141-x64-release:
        BUILD_TOOLSET_VERSION: '141'
      vc142-x64-debug:
        VM_IMAGE_NAME: 'windows-2019'
        CMAKE_GENERATOR: 'Visual Studio 16 2019'
        BUILD_CONFIGURATION: 'debug'
        BUILD_MIX_FOR_DEBUG: 'ON'
        BUILD_TOOLSET_VERSION: '142'
      vc142-x64-release:
        VM_IMAGE_NAME: 'windows-2019'
        CMAKE_GENERATOR: 'Visual Studio 16 2019'
        BUILD_TOOLSET_VERSION: '142'

  variables:
    VM_IMAGE_NAME: 'vs2017-win2016'
    CMAKE_GENERATOR: 'Visual Studio 15 2017'
    BUILD_TOOLSET_VERSION: '141'
    ARCHITECTURE_SUFFIX: '-x64'
    PANDA3D_TOOLS_SUFFIX: 'win64'

  pool:
    vmImage: $(VM_IMAGE_NAME)

  steps:
  # download tools
  - script: curl "https://www.panda3d.org/download/panda3d-1.10.2/panda3d-1.10.2-tools-$(PANDA3D_TOOLS_SUFFIX).zip" -o "panda3d-tools.zip"
    displayName: Download Panda3D Tools

  # extract tools
  - task: ExtractFiles@1
    displayName: Extract Panda3D Tools
    inputs:
      archiveFilePatterns: '$(Build.SourcesDirectory)/panda3d-tools.zip'
      destinationFolder: '$(Build.SourcesDirectory)'
      cleanDestinationFolder: false

  # move tools
  - script: move "$(Build.SourcesDirectory)\panda3d-1.10.2" "$(Build.BinariesDirectory)\thirdparty"
    displayName: Move Panda3D Tools

  # configure & generate
  - task: CMake@1
    inputs:
      cmakeArgs: >-
        .. -G "$(CMAKE_GENERATOR)" -A $(CMAKE_GENERATOR_PLATFORM) -Wno-dev -T "v$(BUILD_TOOLSET_VERSION)"
        -DCMAKE_INSTALL_PREFIX="$(Build.BinariesDirectory)/thirdparty"
        -Dbuild_mixfordebug=$(BUILD_MIX_FOR_DEBUG)

  # build
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --config release

  # install
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --config release --target install

  # packaging
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/thirdparty'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/thirdparty.7z'

  # publish
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(REPO_NAME)-vc$(BUILD_TOOLSET_VERSION)$(ARCHITECTURE_SUFFIX)-$(BUILD_CONFIGURATION)'
